version: '3.7'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: nest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sparrow-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    name: internal
    driver: bridge
volumes:
  mysql-data:  # Define the named volume here